### ISSUE TITLE
Cannot display io_grad in standalone mode

### ISSUE THREAD

**Issue by StarCycle** [spfrommer/torchexplorer#49]
I clone the repo, pip install it and then run the main.py in `examples/minimal_resnet`. It does work.

But if I set the `log` parameter to `io_grad`, it throw the following error:

> /home/pc/.local/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/pc/.local/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
Starting TorchExplorer at http://localhost:5000
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    model(dummy_X).sum().backward()
  File "/home/pc/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/pc/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/pc/.local/lib/python3.8/site-packages/torchvision/models/resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "/home/pc/.local/lib/python3.8/site-packages/torchvision/models/resnet.py", line 270, in _forward_impl
    x = self.relu(x)
  File "/home/pc/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/pc/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/pc/.local/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 101, in forward
    return F.relu(input, inplace=self.inplace)
  File "/home/pc/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 1469, in relu
    result = torch.relu_(input)
RuntimeError: Output 0 of BackwardHookFunctionBackward is a view and is being modified inplace. This view was created inside a custom Function (or because an input was returned as-is) and the autograd logic to handle view+inplace would override the custom backward associated with the custom Function, leading to incorrect gradients. This behavior is forbidden. You can fix this by cloning the output of the custom Function.

**Comment by StarCycle** [comment]
Here is my main.py:

>   1 import torch                                                                                                                                                                                           
  2 import torchvision
  3 import torchexplorer
  4  
  5 model = torchvision.models.resnet18(pretrained=False)
  6 dummy_X = torch.randn(5, 3, 32, 32)
  7  
  8 # Only log input/output and parameter histograms, if you don't want even these set log=[].
  9 torchexplorer.watch(model, log_freq=1, log=['io', 'io_grad', 'params_grad', 'params'], backend='standalone')
 10  
 11 # Do one forwards and backwards pass
 12 model(dummy_X).sum().backward()
 13  
 14 # Your model will be available at http://localhost:5000

**Comment by spfrommer** [comment]
This is expected behavior due to the in-place operations in the ResNet: see "Common Errors 1" in the README.

The following should bypass the in-place operations:

```python
torchexplorer.watch(
    model,
    log_freq=1,
    disable_inplace=True,
    ignore_io_grad_classes=[torchvision.models.resnet.BasicBlock],
    backend='standalone'
)
```

Let me know if this works for you. Note though that the gradient information won't be very meaningful here since we're passing random data to an untrained model, which is why I have it disabled in the demo.
